#THIS SCRIPT EXECUTES AN ANALYSIS OF 2 STUDIES of UKB and FG NS
#THE RESULTS FOR EACH STUDY ARE STORED IN FILES ns_ukb.txt and ns_fg.txt

#LOAD THE FIRST 2 INPUT FILES

# UNCOMMENT THE NEXT LINE TO ENABLE GenomicControl CORRECTION
GENOMICCONTROL ON
SCHEME STDERR
AVERAGEFREQ ON
EFFECT_PRINT_PRECISION 8
STDERR_PRINT_PRECISION 8

# === DESCRIBE AND PROCESS THE 1st INPUT FILE ===
MARKER SNP
ALLELE ALLELE1 ALLELE0
EFFECT BETA
PVALUE P_BOLT_LMM_INF
STDERR SE
FREQLABEL A1FREQ
PROCESS ns_ukb.txt

# === DESCRIBE AND PROCESS THE 2nd INPUT FILE ===
MARKER rsids
ALLELE alt ref
EFFECT beta
STDERR sebeta
FREQLABEL af_alt
PVALUE pval
PROCESS ns_fg.txt

# === ANALYZE ===
OUTFILE meta_ns .txt
ANALYZE HETEROGENEITY

QUIT
